SELECT * FROM NOTICE


INSERT INTO NOTICE(
	CODE,
	TITLE,
	[CONTENT],
	MEMBER_ID)
VALUES(
	'2',
	'T1',
	'TEST TT',
	'ad')

SELECT * FROM 
(
	SELECT
		ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
		NOTICE.* 
		FROM NOTICE WHERE TITLE LIKE '%%'
)N
WHERE NUM BETWEEN 1 AND 10

UPDATE NOTICE SET TITLE='TOTOTOTO', [CONTENT]='HOOOOO' WHERE CODE='1' ;

		
SELECT * FROM 
(
SELECT
ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM, 
NOTICE.* FROM
NOTICE WHERE ${param2} LIKE '%${param3}%') N WHERE NUM BETWEEN
(1+(#{param1}-1)*10) AND ((#{param1}*10))

SELECT * FROM 
(
	SELECT
		ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
		NOTICE.* 
		FROM NOTICE WHERE TITLE LIKE '%%'
)N
WHERE NUM BETWEEN 1 AND 10

SELECT ISNULL(MAX(CAST(CODE AS INT)), 0)+1 AS CODE FROM NOTICE
